#!/bin/sh

down() {
	[[ `pulsemixer --get-mute` == 1 ]] && pulsemixer --unmute
	pulsemixer --max-volume 100 --change-volume -2
  volume=$(pulsemixer --get-volume | cut -d' ' -f1)
  [$volume -gt 0 ] && volume=`expr $volume`  
  dunstify -a "VOLUME" "$volume%" -h int:value:"$volume" -i ~/.config/dunst/assets/ui/volume_down.png -r 2593 -u normal
  canberra-gtk-play -i audio-volume-change -d "changevolume"
}

up() {
	[[ `pulsemixer --get-mute` == 1 ]] && pulsemixer --unmute
	pulsemixer --max-volume 100 --change-volume +2
  volume=$(pulsemixer --get-volume | cut -d' ' -f1)
  [ $volume -lt 1000 ] && volume=`expr $volume`  
  dunstify -a "VOLUME" "$volume%" -h int:value:"$volume" -i ~/.config/dunst/assets/ui/volume_up.png -r 2593 -u normal
  canberra-gtk-play -i audio-volume-change -d "changevolume"
}

mute() {
	if [[ `pulsemixer --get-mute` == 1 ]]; then
    pulsemixer --toggle-mute
    dunstify -a "VOLUME" "UNMUTED" -i ~/.config/dunst/assets/ui/volume_up.png -r 2593 -u normal
  else 
    pulsemixer --toggle-mute
    dunstify -a "VOLUME" "MUTED" -i ~/.config/dunst/assets/ui/volume_muted.svg -r 2593 -u normal
  fi
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
esac
