#!/usr/bin/env bash

CONFIG="$HOME/.config/sway/wofi/config"
STYLE="$HOME/.config/sway/wofi/style.css"
COLORS="$HOME/.config/sway/wofi/colors"

if [[ ! `pidof wofi` ]]; then
	wofi --show drun --prompt 'Apps' --conf ${CONFIG} --style ${STYLE} --color ${COLORS}
else
	pkill wofi
fi
