#!/usr/bin/env bash

CONFIG="$HOME/.config/kitty/kitty.conf"

if [ "$1" == "-f" ]; then
	kitty --app-id='kitty-float' --config="$CONFIG"
elif [ "$1" == "-F" ]; then
	kitty --fullscreen --app-id='kitty-full' --config="$CONFIG"
elif [ "$1" == "-s" ]; then
	kitty --app-id='kitty-float' --config="$CONFIG" \
	--window-size-pixels=$(slurp -b 1B1F28CC -c E06B74ff -s C778DD0D -w 2 -f "%wx%h")
else
	kitty --config="$CONFIG"
fi
