theme = "catppuccin_mocha"

[editor]
auto-completion = true
auto-format = true
auto-pairs = true
auto-save = true
bufferline = "always"
color-modes = true
cursorline = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
line-number = "relative"
middle-click-paste = true
mouse = true
rulers = [100]
shell = ["zsh", "-c"]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "┊"
render = true

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spacer", "file-name", "separator", "spacer", "version-control"]
right = ["spinner", "spacer", "separator", "position", "separator", "spacer", "position-percentage", "spacer", "separator", "file-encoding", "file-type"]
center = ["workspace-diagnostics", "spacer", "diagnostics"]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"

[keys.normal]
q = ":buffer-close"
D = "kill_to_line_end"
G = "goto_last_line"
Q = ":quit!"
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":bn"
S-tab = ":bp"

[keys.normal.space]
o = ":config-open"
r = ":config-reload"
w = ":w"