#!/usr/bin/env bash

IMAGE="$HOME/.config/sway/wallpapers/lockscreen.png"

bg='282a36'	  	bgl='282a36'  		fg='f8f8f2'
red='ff5555'		green='50fa7b'		yellow='f1fa8c'
blue='bd93f9'		magenta='ff79c6'	cyan='8be9fd'
alpha='282a36'

swaylock -f \
	\
	`# General` \
	--show-failed-attempts \
	--hide-keyboard-layout \
	--indicator-caps-lock \
	\
	`# Appearance` \
	--color ${bg} \
	--image ${IMAGE} --scaling 'stretch' \
	--font 'Mononoki Nerd Font' --font-size 18 \
	\
	`# Backspace` \
	--key-hl-color ${green} \
	--caps-lock-key-hl-color ${blue} \
	--bs-hl-color ${red} \
	--caps-lock-bs-hl-color ${red} \
	\
	`# Indicator` \
	--indicator-radius 120 \
	--indicator-thickness 10 \
	\
	`# Inside Circle` \
	--inside-color ${alpha} \
	--inside-clear-color ${alpha} \
	--inside-caps-lock-color ${alpha} \
	--inside-ver-color ${blue} \
	--inside-wrong-color ${red} \
	\
	`# Layout` \
	--layout-bg-color ${cyan} \
	--layout-border-color ${cyan} \
	--layout-text-color ${bg} \
	\
	`# Line` \
	--line-color ${bg} \
	--line-clear-color ${red} \
	--line-caps-lock-color ${bg} \
	--line-ver-color ${bg} \
	--line-wrong-color ${bg} \
	\
	`# Ring` \
	--ring-color ${cyan} \
	--ring-clear-color ${bg} \
	--ring-caps-lock-color ${magenta} \
	--ring-ver-color ${blue} \
	--ring-wrong-color ${red} \
	\
	`# Separator` \
	--separator-color ${bg} \
	\
	`# Text` \
	--text-color ${fg} \
	--text-clear-color ${fg} \
	--text-caps-lock-color ${fg} \
	--text-ver-color ${bg} \
	--text-wrong-color ${bg}
