#!/usr/bin/env bash

CONFIG="$HOME/.config/sway/wofi/config"
STYLE="$HOME/.config/sway/wofi/style.css"
COLORS="$HOME/.config/sway/wofi/colors"

wofi_command="wofi --show dmenu \
			--conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
			--width=300 --height=205 \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--define=matching=fuzzy"

uptime=$(uptime -p | sed -e 's/up //g')

shutdown="⏻ Shutdown"
reboot=" Restart"
lock=" Lock"
suspend="⏾ Sleep"
logout=" Logout"

cdialog () {
	yad --title='Confirm?' --borders=15 --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="Are you sure?" --text-align=center
}

open_menu () {
	options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

	chosen="$(echo -e "$options" | $wofi_command --prompt "Uptime - $uptime")"
	case $chosen in
		$shutdown)
			cdialog
			if [[ "$?" == 0 ]]; then
				systemctl poweroff
			else
				exit
			fi
			;;
		$reboot)
			cdialog
			if [[ "$?" == 0 ]]; then
				systemctl reboot
			else
				exit
			fi
			;;
		$lock)
			~/.config/sway/scripts/lockscreen
			;;
		$suspend)
			cdialog
			if [[ "$?" == 0 ]]; then
				mpc -q pause
				pulsemixer --mute
				~/.config/sway/scripts/lockscreen
				systemctl suspend
			else
				exit
			fi
			;;
		$logout)
			cdialog
			if [[ "$?" == 0 ]]; then
				swaymsg exit
			else
				exit
			fi
			;;
	esac
}

if [[ ! `pidof wofi` ]]; then
	open_menu
else
	pkill wofi
fi

