#!/usr/bin/env bash

_ps=(waybar mako mpd xfce-polkit)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

/usr/lib/xfce-polkit/xfce-polkit &

~/.config/sway/scripts/notifications &

~/.config/sway/scripts/statusbar &

nm-applet --indicator &

exec mpd &
